{% set name = "CppHeaderParser" %}
{% set version = "2.7.4" %}
{% set sha256 = "382b30416d95b0a5e8502b214810dcac2a56432917e2651447d3abe253e3cc42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip

  run:
    - python >={{ python_min }}
    - ply

test:
  requires:
    - python {{ python_min }}
  imports:
    - CppHeaderParser

about:
  home: http://senexcanis.com/open-source/cppheaderparser/
  license: BSD
  license_file: LICENSE.txt
  summary: 'Parse C++ header files and generate a data structure representing the class'
  doc_url: http://pydoc.net/CppHeaderParser/latest/
  dev_url: https://bitbucket.org/senex/cppheaderparser

extra:
  recipe-maintainers:
    - tigarmo
