travis:
  secure:
    BINSTAR_TOKEN: CbaVJq+exDIwzI+JJroi7QIQaGjslWytcWDLGRAH3e65+d4nLrK3japSAiF+W2oSgfqEeVN6P8fVGoNLTuDxjaLIAnFGZYfkyjD2Hdf8fmwmTTgakSuZxsE+caPKd+Om29641S0sEHSrzu4OY6tnFA+d27Ybsz6ahfc1LgzyH/vAODkTt9GYIgmTe5kaeHhEW8Uk4+NXN9tAktwH91GU0b2xXXHUDrbcX5D5QaE8TXiwTiWT/YTRR+YjkD7LG+axWxKrrRJXcAOh44AbpoNXd5ZWe3ceQYxSH0Qy3bGxLRgk5elYSIDBO+NIcXgT1AtnDyMyN8U/36qTpNOb5Sfr6GN0oS6m9VFYLDgjuvkRZtfrVpxG50Wjfr6vPOLObiVbyeWNMhRDN1pKLNVx3TxjFqYiC6Xj84FPbp1iPdCWZZZq8mKSaQvDaefGKEeQwIrHcJzQ7GB1WnmELCwjRLCUs9l3HfYJGvAKCzLbO2xnoRm9t/NnpIzABqPg4L9lp/JHLvW6fpvQd97copjhCNVWJK4PKSnw7VZQIwQqifeB0MOChmcyjwqMaq028jhuqYk+YkjifmeSIdSdDU8ErL+XvrjRhSgB2C6HNL35Tn5AQz/ycBf9zFy+6U4PJmJSWyGzSkEGfMi1LULSpHTyuUrDG9L2tuyLTVOo/ORMh6o1+F8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
