travis:
  secure:
    BINSTAR_TOKEN: PPCYOtuEJ0Fh3gXKsLMzW38qvSDxGgN+FO1+n1D4CUKf0lo0yRUDr71OFZg0Ocy4wKQS2O1HlvxooDTjibI82NRcQ1lG7LrMyAeSR6SeGIkTUZk31Al7QgTOqIDMhdDmefF/TOIswHVkAbR4QIb9FrAeZ2UMY2z+iuYCz/4nlbLt0UdeBNn9IodECNrMjB4E7NF/7h0Ln8EVstC76nVW1XNbXvP3k4Ndr+IeyQxHubUTaQlDN2eT6L/kCrz6E9viTtmYKHdUxJBPd4JhokqhRu5iEzIql2qkse/chzmKqeKoXiv45gz75UlgXqW5IDfbdRMIkXD579ueClWTZF/AeLVJxCE7KKhZh7AQB5urOt1j2W5RFswc43GKgXhcctgyKyEgiKEx4HotPd1jloPNiEyNuR9p2m7tMhfuK4Mjc2OQk0bOcPsmfBys9GlH09BU4XScBn2P4Q9BaHGgDD7LFrrQdQKN+OwmAj/NJcZ15rO0m7Hjp9NdZpHBkmAgE/MznpVzIcvMTavDzy66b3mGvYGo9zOl1VHOxyASksnufz3v9PEm2EPOVpgBuyhvQ2BLINdk+0PsRsHqLG5rLyCRuQJsyBgEWDgnXlFHVMfbQq3R2gRvhYP9ZRTRER9x/DcWy+pQ4bKkL/nPh15eS0AbpROaOv9jnk3+pjwBmRUFBiw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
